#pragma once
#include <Windows.h>
#include <chrono>
#include <thread>
#include <cstdint>
#include <map>
#include <deque>
#include <unordered_map>
#include <functional>
#include <fstream>
#include <cstdio>
#include <cmath>
#include <algorithm>
#include "fnv1a.h"
#include "util.h"
#include "minhook.h"
#include "xorstr.h"
#include "tinyformat.h"
#include "lazy_importer.h"
#include "pattern.h"
#include "pad.h"
#include "vector.h"
#include "matrix.h"
#include "math.h"
#include "usercmd.h"
#include "sdk.h"
#include "interfaces.h"
#include "event_handler.h"
#include "logging.h"
#include "netvars.h"
#include "entity.h"
#include "globals.h"
#include "render.h"
#include "visuals.h"
#include "hooks.h"